### ISSUE TITLE
"Missing files" alert when running simulate.jl

### ISSUE THREAD

**Issue by LaurelineJ** [AmericasWater/awash#61]
The message we get when running simulate.jl tells us to run optimize-surface.jl. This message is given if the captures input file for the reservoirs operation does not exist.
However, in its default state, optimize surface does not optimize reservoirs operation. 
My idea would be to change the check in model-waterdemand.jl to be instead: 
1) verifying that the withdrawals file exist and is of the correct size
2) if reservoirs are operated, that the captures file exist.

**Comment by jrising** [comment]
I just opened the PR above to fix this.

Separately (though I also put it in that PR), I think that optimize-surface should include reservoir management.  There was a `#XXX` comment next to the `false`, which is coder-speak for "this shouldn't be this way, but needed to be done temporarily".
