### ISSUE TITLE
Clean up missingcanals in countydraws

### ISSUE THREAD

**Issue by jrising** [AmericasWater/awash#9]
How is the new `countydraws.RData` file generated?  I ask, because I think there's some cleaning up to do, and how I'd suggest doing it depends on that.

If there is a single R script that generates countydraws from original data, then I just think we should clean up the `exdist` column.  It currently has values like "fipssource 1073".  That column (which is defined somewhere...) is the distance outside of the county that the canal travels.  It can be NA, but it shouldn't be a string.  We can add another column for this information, though if it's just the FIPS code of the county that the specified gauge is in, it doesn't seem so important.

If the script that generates this file actually takes the original file and addes the missingcanals entries to it, then I propose that we split out the missingcanals from the countydraws.  That way each one can be separately made from a single script.

**Comment by jrising** [comment]
@LaurelineJ Do you know what changed with your version of countydraws?  Should we be rolling back to the pre-Aug-2016 version of countydraws?

**Comment by LaurelineJ** [comment]
Here is the script that was used to augment countydraws: [link](https://github.com/AmericasWater/awash/blob/5eb9c6a9ca69bc6b97c109d06e1bfb1e2b9215ab/data/prepared/script_incorporation_missing_data.R)
In the waternet notebook, explanations are given to explain the process that was used: [link](https://github.com/AmericasWater/awash/blob/5eb9c6a9ca69bc6b97c109d06e1bfb1e2b9215ab/docs/waternet.ipynb) - section missing canals, after developping/contributing.
And here is the list of counties for which the cumbersome process of identifying connections had been done: [link](https://github.com/AmericasWater/awash/blob/5eb9c6a9ca69bc6b97c109d06e1bfb1e2b9215ab/data/prepared/canals.txt) - only for 140 of the counties.

What do you think? I think there is a need to also explain what has been done to transform the 2010 USGS to 2000 shapefile. I did this I believe.

**Comment by jrising** [comment]
Great, thank you for this.  I want to merge this together with the "non-missing" canals code and make the "exdist" column consistent.

**Comment by jrising** [comment]
Do you know why you have some canals going from Texas to Maryland?  Your canals are in cyan.

![network-county](https://user-images.githubusercontent.com/579448/38107602-694102ee-3360-11e8-906c-106eb4ada45b.png)

**Comment by jrising** [comment]
This is done, as far as v. 0.5 is concerned.  @LaurelineJ I suggest you open another issue for your new canal work.
